# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for Tree project
      run: dotnet restore binary-tree-rambling-heavy-metal-concert/Tree/Tree.csproj
    - name: Build Tree project
      run: dotnet build binary-tree-rambling-heavy-metal-concert/Tree/Tree.csproj --no-restore
    - name: Restore dependencies for tests
      run: dotnet restore binary-tree-things-tests/binary-tree-things-tests.csproj
    - name: Build tests
      run: dotnet build binary-tree-rambling-heavy-metal-concert/binary-tree-things-tests/binary-tree-things-tests.csproj --no-restore
    - name: Test
      run: dotnet test binary-tree-rambling-heavy-metal-concert/binary-tree-things-tests/binary-tree-things-tests.csproj --no-build --verbosity normal
